server:
  port: 8072

spring:
  application:
    name: telegram-agent

  datasource:
    url: jdbc:postgresql://localhost:5432/messenger
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate
    show-sql: true
    properties.hibernate.format_sql: true

  liquibase:
    enabled: false
#    change-log: classpath:db/changelog/db.changelog-master.yml

  kafka:
    bootstrap-servers: localhost:29092

    consumer:
      group-id: telegram-agent
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  cloud:
    openfeign:
      retry:
        enabled: true

resilience4j:
  retry:
    instances:
      getMessageFromTelegramAgent:
        maxAttempts: 3
        waitDuration: 500ms
        retryExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
        failAfterMaxAttempts: true

      default:
        maxAttempts: 3
        waitDuration: 500ms
        retryExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
        failAfterMaxAttempts: true


  ratelimiter:
    instances:
      getMessageFromTelegramAgent:
        limitForPeriod: 10
        limitRefreshPeriod: 2s
        timeoutDuration: 0s

app:
  kafka:
    topics:
      telegram-agent:
        name: TELEGRAM_AYSNC_MESSAGE
        group-id: telegram-agent


management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus

  tracing:
    sampling:
      probability: 1.0

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces