application:
  title: Messenger Gate Way
  version: 0.0.1-snapshot

server:
  port: 8080

management:
  endpoint:
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include: "*"
#        exclude: "*"



spring:
  cloud:
    gateway:
      routes:

        - id: distributor-service
          uri: http://distributor-service:8080
          predicates:
            - Path=/api/users/**

