application:
  title: Messenger Gate Way
  version: 0.0.1-snapshot

server:
  port: 8070

management:
  endpoint:
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include: "*"
#        exclude: "*"

spring:
  cloud:
    gateway:
      server:
        webflux:

          routes:
            - id: distributor-service
              uri: http://localhost:8071
              predicates:
                - Path=/api/v1/messages/**

services:
  distributor:
    url: http://localhost:8071
