application:
  title: Messenger Gate Way
  version: 0.0.1-snapshot

server:
  port: 8070

management:
  endpoint:
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include: "*"
#        exclude: "*"

spring:
  cloud:
    gateway:
      routes:

        - id: distributor-service
          uri: localhost:8070
          predicates:
            - Path=/api/users/**

