server:
  port: 8071

spring:
  application:
    name: Distributor
  datasource:
    url: jdbc:h2:mem:distributor
    driver-class-name: org.h2.Driver
    username: sa
    password: pass

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: none
    show-sql: true
    properties.hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

resilience4j:
  circuitbreaker:
    instances:
      telegramSender: #  ${telegram-sender.service.name}
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 50
        minimumNumberOfCalls: 5
        failureRateThreshold: 50  # 50%
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50  # 50%
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3


application:
  title: Messenger Distributor
  version: 0.0.1-snapshot


springdoc:
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui-custom.html
    enabled: true


telegram-sender:
  service:
    name: telegramSender
    url: http://telegram-sender:8072