server:
  port: 8071

spring:
  application:
    name: Distributor
  datasource:
    url: jdbc:postgresql://localhost:5432/messenger
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate
    show-sql: true
    properties.hibernate.format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  kafka:
    bootstrap-servers: localhost:9092

  data:
    redis:
      host: localhost
      port: 6379

resilience4j:
  circuitbreaker:
    instances:
      telegramAgent:    #  ${telegram-agent.service.name}
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 50
        minimumNumberOfCalls: 5
        failureRateThreshold: 50  # 50%
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50  # 50%
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3

application:
  title: Messenger Distributor
  version: 0.0.1-snapshot


springdoc:
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui-custom.html
    enabled: true

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.hibernate.tool.schema: DEBUG
    liquibase: DEBUG
    org.springframework.boot.autoconfigure.liquibase: DEBUG

telegram-Agent:
  service:
    name: telegramAgent
    url: http://localhost:8072
